apiVersion: v2
name: unifi-network-application
version: 10.0.162
description: A Helm chart Unifi Network Application
appVersion: 10.0.162
icon: https://raw.githubusercontent.com/dbrosy/rancher-charts-v2/main/charts/unifi-network-application/logo.png